name: linux-aarch64-cpu-gcc
on: [push, pull_request]
jobs:
  linux-gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: git
      run: cd ./cplussharp/vscode/test && git submodule update --init  --recursive
    - name: cache-qemu
      id: cache-qemu
      uses: actions/cache@v1
      with:
        path: qemu-install
        key: qemu-aarch64-install-1
    - name: checkout-qemu
      if: steps.cache-qemu.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: qemu/qemu
        path: qemu
        ref: 8746309137ba470d1b2e8f5ce86ac228625db940
    - name: qemu
      if: steps.cache-qemu.outputs.cache-hit != 'true'
      run: |
        cd qemu
        ./configure --prefix=install --target-list=aarch64-linux-user --disable-system
        make -j2
        make install
        cp -r aarch64-linux-user/install $GITHUB_WORKSPACE/qemu-install

    - name: aarch64-gnu-toolchain
      run: |
        sudo apt-get update
        sudo apt-get install g++-aarch64-linux-gnu
    - name: cache-boost
      id: cache-boost
      uses: actions/cache@v1
      with:
        path: "cplussharp/vscode/test/boost-install"
        key: boost-install
    - name: boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.zip  >/dev/null 2>&1
        unzip boost_1_72_0.zip >/dev/null 2>&1
        cd boost_1_72_0  && ./bootstrap.sh && echo  "using gcc : arm64 : aarch64-linux-gnu-g++ ; " >>  project-config.jam && ./b2  -j2 --with-date_time --with-filesystem --with-system --with-thread --with-regex link=static runtime-link=static         && ./b2   install  architecture=arm  address-model=64 --without-python  --prefix="$env:GITHUB_WORKSPACE/cplussharp/vscode/test/boost-install"  link=static runtime-link=static  threading=multi --toolset=gcc-arm64
    - name: configure
      run: cd ./cplussharp/vscode/test && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/aarch64-linux-gnu.toolchain.cmake -DNCNN_ARM82=OFF -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF -DNCNN_BUILD_TESTS=ON ..
    - name: build
      run: cd ./cplussharp/vscode/test && cmake --build build -j 2

    #- name: test
    #  run: |
    #    export PATH=$GITHUB_WORKSPACE/qemu-install/bin:$PATH
    #    cd ./cplussharp/vscode/test && cd build
    #    TESTS_EXECUTABLE_LOADER=qemu-aarch64 TESTS_EXECUTABLE_LOADER_ARGUMENTS="-L;/usr/aarch64-linux-gnu" ctest --output-on-failure -j 2

  