name: linux-x64-cpu-gcc
on: [push, pull_request]
jobs:
  linux-gcc:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    #- name: update
    #  run: sudo apt-get update
    #- name: protobuf
    #  run: sudo apt-get install libprotobuf-dev protobuf-compiler libopencv-dev
    - name: path
      run: cd c++chsarp/vscode/test
    - name: configure
      run: mkdir build && cd build && cmake -DNCNN_BUILD_TESTS=ON ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest --output-on-failure -j 2

  
